function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(GraphPlot.random_layout, (Graphs.AbstractGraph{KeyVertex},))
    precompile(GraphPlot.random_layout, (Graphs.AbstractGraph{ExVertex},))
    precompile(GraphPlot.circular_layout, (Graphs.AbstractGraph{KeyVertex},))
    precompile(GraphPlot.circular_layout, (Graphs.AbstractGraph{ExVertex},))
    precompile(GraphPlot.spring_layout, (Graphs.AbstractGraph{KeyVertex}, Float64, Float64, Float64,))
    precompile(GraphPlot.spring_layout, (Graphs.AbstractGraph{ExVertex}, Float64, Float64, Float64,))
    precompile(GraphPlot.spring_layout, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.spring_layout, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.shell_layout, (Graphs.AbstractGraph{KeyVertex}, Void,))
    precompile(GraphPlot.shell_layout, (Graphs.AbstractGraph{ExVertex}, Void,))
    precompile(GraphPlot.shell_layout, (Graphs.AbstractGraph{KeyVertex}, Vector{Vector{Int}},))
    precompile(GraphPlot.shell_layout, (Graphs.AbstractGraph{ExVertex}, Void, Vector{Vector{Int}},))
    precompile(GraphPlot.spectral_layout, (Graphs.AbstractGraph{KeyVertex}, Void,))
    precompile(GraphPlot.spectral_layout, (Graphs.AbstractGraph{ExVertex}, Void,))
    precompile(GraphPlot.spectral_layout, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64},))
    precompile(GraphPlot.spectral_layout, (Graphs.AbstractGraph{ExVertex}, Vector{Float64},))
    precompile(GraphPlot.stressmajorize_layout, (Graphs.AbstractGraph{KeyVertex}, Int, Void, Vector{Float64}, Int,))
    precompile(GraphPlot.spectral_layout, (Graphs.AbstractGraph{ExVertex}, Int, Void, Vector{Float64}, Int,))
    precompile(GraphPlot.spectral_layout, (Graphs.AbstractGraph{KeyVertex}, Int, Vector{Float64}, Vector{Float64}, Int,))
    precompile(GraphPlot.spectral_layout, (Graphs.AbstractGraph{ExVertex}, Int, Vector{Float64}, Vector{Float64}, Int,))
    precompile(GraphPlot.graphline, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, Float64,))
    precompile(GraphPlot.graphline, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, Float64,))
    precompile(GraphPlot.graphline, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.graphline, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.graphline, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Vector{Float64},))
    precompile(GraphPlot.graphline, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Vector{Float64},))
    precompile(GraphPlot.graphline, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Float64,))
    precompile(GraphPlot.graphline, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Float64,))
    precompile(GraphPlot.graphcurve, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.graphcurve, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.graphcurve, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64, Float64,))
    precompile(GraphPlot.graphcurve, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64, Float64,))
    precompile(GraphPlot.graphcurve, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64,))
    precompile(GraphPlot.graphcurve, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64,))
    precompile(GraphPlot.graphcurve, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64}, Float64, Float64,))
    precompile(GraphPlot.graphcurve, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64}, Float64, Float64,))
    precompile(GraphPlot.arrowcoords, (Float64, Float64, Float64, Float64, Float64,))
    precompile(GraphPlot.curvearrowcoords1, (Float64, Float64, Float64, Float64, Float64, Float64,))
    precompile(GraphPlot.curvearrowcoords2, (Float64, Float64, Float64, Float64, Float64, Float64,))
    precompile(GraphPlot.curveedge, (Float64, Float64, Float64, Float64, Float64,))
    precompile(GraphPlot.graphfamous, (UTF8String,))
    precompile(GraphPlot.readedgelist, (UTF8String, Bool, Int,))
    precompile(GraphPlot.gplot, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64},))
    precompile(GraphPlot.gplot, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64},))
    precompile(GraphPlot.gplothtml, (Graphs.AbstractGraph{KeyVertex}, Vector{Float64}, Vector{Float64},))
    precompile(GraphPlot.gplothtml, (Graphs.AbstractGraph{ExVertex}, Vector{Float64}, Vector{Float64},))

    precompile(GraphPlot.random_layout, (LightGraphs.SimpleGraph,))
    precompile(GraphPlot.circular_layout, (LightGraphs.SimpleGraph,))
    precompile(GraphPlot.spring_layout, (LightGraphs.SimpleGraph, Float64, Float64, Float64,))
    precompile(GraphPlot.spring_layout, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.shell_layout, (LightGraphs.SimpleGraph, Void,))
    precompile(GraphPlot.shell_layout, (LightGraphs.SimpleGraph, Vector{Vector{Int}},))
    precompile(GraphPlot.spectral_layout, (LightGraphs.SimpleGraph, Void,))
    precompile(GraphPlot.spectral_layout, (LightGraphs.SimpleGraph, Vector{Float64},))
    precompile(GraphPlot.stressmajorize_layout, (LightGraphs.SimpleGraph, Int, Void, Vector{Float64}, Int,))
    precompile(GraphPlot.spectral_layout, (LightGraphs.SimpleGraph, Int, Vector{Float64}, Vector{Float64}, Int,))
    precompile(GraphPlot.graphline, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, Float64,))
    precompile(GraphPlot.graphline, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.graphline, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Vector{Float64},))
    precompile(GraphPlot.graphline, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Float64,))
    precompile(GraphPlot.graphcurve, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64,))
    precompile(GraphPlot.graphcurve, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Float64, Float64, Float64, Float64,))
    precompile(GraphPlot.graphcurve, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64,))
    precompile(GraphPlot.graphcurve, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64}, Float64, Float64,))
    precompile(GraphPlot.gplot, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64},))
    precompile(GraphPlot.gplothtml, (LightGraphs.SimpleGraph, Vector{Float64}, Vector{Float64},))
end
